### ISSUE TITLE
aiodocker can't see aiohttp during pip install

### ISSUE THREAD

**Issue by konklone** [paultag/moxie#56]
During `pip install -r requirements.txt`, `aiohttp` installs successfully from git, but then `aiodocker` doesn't see it during install/compilation:

```
Obtaining aiohttp from git+https://github.com/KeepSafe/aiohttp#egg=aiohttp (from -r requirements.txt (line 6))
  Updating /home/eric/.virtualenvs/moxie/src/aiohttp clone
  Running setup.py (path:/home/eric/.virtualenvs/moxie/src/aiohttp/setup.py) egg_info for package aiohttp
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'aiohttp/_multidict.html'
    warning: no previously-included files found matching 'aiohttp/_multidict.*.so'
    warning: no previously-included files found matching 'aiohttp/_multidict.pyd'
    warning: no previously-included files found matching 'aiohttp/_multidict.*.pyd'
    warning: no previously-included files found matching 'aiohttp/_websocket.html'
    warning: no previously-included files found matching 'aiohttp/_websocket.*.so'
    warning: no previously-included files found matching 'aiohttp/_websocket.pyd'
    warning: no previously-included files found matching 'aiohttp/_websocket.*.pyd'
  Installing extra requirements: 'egg'
Downloading/unpacking aiodocker (from -r requirements.txt (line 7))
  Downloading aiodocker-0.6.tar.gz
  Running setup.py (path:/home/eric/.virtualenvs/moxie/build/aiodocker/setup.py) egg_info for package aiodocker
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/eric/.virtualenvs/moxie/build/aiodocker/setup.py", line 4, in <module>
        from aiodocker import __version__
      File "/home/eric/.virtualenvs/moxie/build/aiodocker/aiodocker/__init__.py", line 3, in <module>
        from .docker import Docker
      File "/home/eric/.virtualenvs/moxie/build/aiodocker/aiodocker/docker.py", line 5, in <module>
        import aiohttp
    ImportError: No module named 'aiohttp'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/eric/.virtualenvs/moxie/build/aiodocker/setup.py", line 4, in <module>

    from aiodocker import __version__

  File "/home/eric/.virtualenvs/moxie/build/aiodocker/aiodocker/__init__.py", line 3, in <module>

    from .docker import Docker

  File "/home/eric/.virtualenvs/moxie/build/aiodocker/aiodocker/docker.py", line 5, in <module>

    import aiohttp

ImportError: No module named 'aiohttp'
```

**Comment by paultag** [comment]
:+1: thanks!

**Comment by konklone** [comment]
Note: I just tried using the PyPi version of `aiohttp` instead of from git (since there have been several releases since you last touched that line in `requirements.txt`) and got an identical error.

**Comment by konklone** [comment]
And, if I do `pip install aiohttp`, then `pip install aiodocker`, these work. (And I can then do `pip install -r requirements.txt` successfully, using cached stuff.)

It looks like the `import aiohttp` line in `aiodocker` is being executed during the initial download step of `pip install`, so that when it does the download step on each package in turn during `pip install`, `aiohttp` has been downloaded and not installed, and `aiodocker` isn't ready for that. I'm not confident enough about how `pip install` works to research much further, I think.
